version: '3'
services:
  mall-mysql:
    image: mysql:5.7
    container_name: mall-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mall
      MYSQL_USER: mall
      MYSQL_PASSWORD: mall
    ports:
      - "3306:3306"

  mall-redis:
    image: redis:7.0
    container_name: mall-redis
    ports:
      - "6379:6379"

  mall-mongodb:
    image: mongo:5.0
    container_name: mall-mongodb
    ports:
      - "27017:27017"

  mall-rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: mall-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mall
      RABBITMQ_DEFAULT_PASS: mall
    volumes:
      - /mydata/rabbitmq/data:/var/lib/rabbitmq

  mall-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: mall-elasticsearch
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  mall-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: mall-kibana
    ports:
      - "5601:5601"
    environment:
      - "elasticsearch.hosts=http://es:9200"
    links:
      - elasticsearch:es
    depends_on:
      - mall-elasticsearch

  mall-logstash:
    image: docker.elastic.co/logstash/logstash:7.17.3
    container_name: mall-logstash
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
    environment:
      - "xpack.monitoring.enabled=false"
    volumes:
      - /mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - mall-elasticsearch
    links:
      - elasticsearch:es

  mall-nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - /mydata/nginx/conf:/etc/nginx # Mount the configuration file directory
      - /mydata/nginx/html:/usr/share/nginx/html # Mount the static resource root directory
      - /mydata/nginx/logs:/var/log/nginx # Mount the log file directory
    ports:
      - 80:80

  mall-minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    volumes:
      - /mydata/minio/data:/data
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - 9090:9000
      - 9001:9001