spring:
  application:
    name: mall-admin
  profiles:
    active: dev # Default to development environment
  servlet:
    multipart:
      enabled: true # Enable file upload
      max-file-size: 10MB # Limit file upload size to 10M
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization # The request header where the JWT is stored
  secret: mall-admin-secret # The key used for JWT encryption and decryption
  expiration: 604800 # The expiration time of the JWT (60*60*24*7)
  tokenHead: 'Bearer '  # The head of the JWT payload

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24 hours

secure:
  ignored:
    urls: # Security path whitelist
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # The access domain name of OSS external service
    accessKeyId: test # User identifier used in access identity authentication
    accessKeySecret: test # The key used by the user to encrypt the signature string and OSS to verify the signature string
    bucketName: macro-oss # The storage space of OSS
    policy:
      expire: 300 # Signature validity period (S)
    maxSize: 10 # Upload file size (M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # The callback address after the file upload is successful
    dir:
      prefix: mall/images/ # The prefix of the upload folder path
